name: nf-core-circrna-1.0.0
channels:
  - bioconda
  - agbiome
  - conda-forge
  - defaults
dependencies:
  - bbtools=37.62
  - bedtools=2.29.2
  - bioconductor-apeglm=1.8.0
  - bioconductor-biomart=2.42.0
  - bioconductor-complexheatmap=2.2.0
  - bioconductor-deseq2=1.26.0
  - bioconductor-enhancedvolcano=1.4.0
  - bioconductor-ihw=1.14.0
  - bioconductor-org.hs.eg.db=3.10.0
  - bioconductor-pcatools=1.2.0
  - bioconductor-tximport=1.14.0
  - bowtie=1.2.3
  - bowtie2=2.3.5.1
  - bwa=0.7.17
  - circexplorer2=2.3.8
  - cufflinks=2.2.1
  - hisat2=2.2.0
  - java-jdk=8.0.92
  - mapsplice=2.2.1
  - miranda=3.3a
  - openjdk=11.0.8
  - perl=5.26.2
  - picard=2.24.1
  - pip=20.0.2
  - python=2.7.15
  - conda-forge::r-argparser=0.6
  - r-base=3.6.3
  - conda-forge::r-circlize=0.4.12
  - conda-forge::r-dplyr=1.0.3
  - conda-forge::r-ggplot2=3.3.3
  - r-ggpubr=0.4.0
  - conda-forge::r-gplots=3.1.1
  - conda-forge::r-pheatmap=1.0.12
  - r-plyr=1.8.6
  - r-pvclust=2.2_0
  - r-rcolorbrewer=1.1_2
  - samtools=1.10
  - star=2.7.7a
  - stringtie=2.1.1
  - tophat=2.1.1
  - ucsc-bedgraphtobigwig=357
  - ucsc-bedtobigbed=357
  - ucsc-genepredtobed=377
  - ucsc-genepredtogtf=377
  - ucsc-gtftogenepred=377
  - viennarna=2.4.17
  - pip:
    - argparse==1.2.1
    - ciriquant==1.1.1
    - numexpr==2.6.9
    - numpy==1.16.4
    - pysam==0.15.2
    - pyyaml==5.1.1
    - scikit-learn==0.20.3
    - scipy==1.2.2
